### ISSUE TITLE
Error: No module named 'omni.anim.graph.core' when following the setup instructions

### ISSUE THREAD

**Issue by deathpoker** [dillonloh/AdaVLN#2]
Dear Authors：
Thank you for your work on this project—it’s incredibly helpful and inspiring! I have been trying to set it up following the README instructions, but I’ve encountered an issue that I’m unsure how to resolve. I would greatly appreciate your guidance.

I encountered an issue while setting up the project. Specifically, after following the installation steps in the README, I replaced the specified directories as instructed. However, I noticed that the new directory structure is different from the original directory. I linked the parts of the directories that seemed structurally similar. After completing the setup, I encountered the following error when running the project: Error: No module named 'omni.anim.graph.core'.

**Comment by dillonloh** [comment]
Hi there, apologies for the delayed response.

Could you share more information about your current directory structure, and at which stage do you encounter the specified error? We can debug it more accurately with more information.

Thanks!

**Comment by deathpoker** [comment]
Hi,
Apologies for the delayed response. I have been busy with other tasks recently.
Here is the error I encountered:

2025-02-07 07:24:53 [8,507ms] [Error] [omni.ext._impl.custom_importer] Failed to import python module omni.isaac.examples.AdaVLN. Error: No module named 'omni.anim.graph.core'. Traceback:
Traceback (most recent call last):
  File "/home/peiyang/.local/share/ov/pkg/isaac-sim-4.2.0/kit/kernel/py/omni/ext/_impl/custom_importer.py", line 76, in import_module
    return importlib.import_module(name)
  File "/home/peiyang/.local/share/ov/pkg/isaac-sim-4.2.0/kit/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/peiyang/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.examples/omni/isaac/examples/AdaVLN/__init__.py", line 10, in <module>
    from omni.isaac.examples.AdaVLN.ada_vln import AdaVLN
  File "/home/peiyang/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.examples/omni/isaac/examples/AdaVLN/ada_vln.py", line 11, in <module>
    import omni.anim.graph.core as ag
ModuleNotFoundError: No module named 'omni.anim.graph.core'

It appears that the module omni.anim.graph.core is not found, which causes the extension to fail to load.
Please let me know if you need further details to help troubleshoot or if there are any additional steps I can take on my end.
Thanks again for your assistance!
